version: '2'
services:
  proxy:
    container_name: proxy
    build:
      context: .
    environment:
      - DATA_CONTAINER=true
    stdin_open: true
    restart: always

    ports:
      - '80:8888'
    volumes:
       - /etc/${COMPANY_NAME}
       - /var/www/${COMPANY_NAME}/Data
      # - ./var/log/ds:/var/log/${COMPANY_NAME}
      # - ./var/lib/ds:/var/lib/${COMPANY_NAME}
      # - ./var/log/nginx:/var/log/nginx
      # - ./var/lib/example:/var/www/${COMPANY_NAME}/documentserver-example/public/files
       - /usr/share/fonts
       - ./local.json:/etc/${COMPANY_NAME}/documentserver/local.json
       - ./http-upstream.conf:/etc/nginx/includes/http-upstream.conf
       
  ds:
    build:
      context: .
    container_name: ds
    depends_on:
      - proxy
      - postgresql
      - redis
      - rabbitmq
    environment:
      - DATA_CONTAINER_HOST=proxy
    stdin_open: true
    restart: always
    expose:
      - '3000'
      - '8000'
      - '8080'
    volumes_from:
     - proxy

  redis:
    container_name: redis
    image: redis
    restart: always
    expose:
      - '6379'

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq
    restart: always
    expose:
      - '5672'

  postgresql:
    container_name: postgresql
    image: postgres:9.5
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
    restart: always
    expose:
      - '5432'
    volumes:
      - postgresql_data:/var/lib/postgresql

volumes:
  postgresql_data:
