#!/bin/bash

export PRODUCT_VERSION=$DOCKER_TAG
export DOCKER_BUILDKIT=1
docker-compose build \
  --build-arg PRODUCT_EDITION=$PRODUCT_EDITION \
  --build-arg PRODUCT_URL=$PRODUCT_URL \
  --build-arg COMPANY_NAME=$COMPANY_NAME_ARG
