### This workflow setup instance then build and push images ###
name: Build 

on:
  push:
    tags:
      - "v*"
      
jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        edition: [ "-ee" ]
        images: [ "proxy docservice converter" ]
    steps:
      - name: Checkout code 
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
     
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Get Tag Name
        id: tag_name
        run: |
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      - name: Set build variables
        run: |
          echo "DOCKER_TAG=$(echo ${{ steps.tag_name.outputs.SOURCE_TAG }} | sed 's/^.//')" >> $GITHUB_ENV
          echo "REPO_NAME=${{ github.event.repository_owner.name }}" >> $GITHUB_ENV

      - name: Set package version vairable for specific repository
        run: |
          if [[ ${{ env.REPO_NAME }} == "Docker-Docs-ASC" ]]; then 
             echo "PACKAGE_VERSION=$(echo $DOCKER_TAG | sed -E 's/(.*)\./\1-/' | sed -E 's/^/-/')" >> $GITHUB_ENV

          #- name: Build Community-Edition
          # run: |
          # PRODUCT_EDITION=${{ matrix.edition }} \
          # TAG=${DOCKER_TAG} \
          # COMPANY_NAME=${{ secrets.COMPANY_NAME }} \
          # PRODUCT_URL=${{ secrets.PRODUCT_URL }}${PACKAGE_VERSION}.TARGETARCH.rpm \
          # ACCOUNT_NAME=${{ secrets.ACCOUNT_NAME }} \
          #    docker buildx bake \
          #    -f docker-bake.hcl ${{ matrix.images }} \
          #    --push
          # shell: bash
       
      - name: Build and push images 
        uses: docker/bake-action@v2.1.0
        with:
          set: |
            proxy.tags=docker.io/${{ secrets.ACCOUNT_NAME }}/docs-proxy${{ matrix.edition }}:${{ env.DOCKER_TAG }}
            converter.tags=docker.io/${{ secrets.ACCOUNT_NAME }}/docs-converter${{ matrix.edition }}:${{ env.DOCKER_TAG }} 
            docservice.tags=docker.io/${{ secrets.ACCOUNT_NAME }}/docs-docservice${{ matrix.edition }}:${{ env.DOCKER_TAG }}
            *.args.PRODUCT_EDITION=${{ matrix.edition }}
            *.args.COMPANY_NAME=${{ secrets.COMPANY_NAME }}
            *.args.PRODUCT_URL=${{ secrets.PRODUCT_URL }}${{ matrix.edition }}${{ env.PACKAGE_VERSION }}.TARGETARCH.rpm
          push: true
          files: docker-bake.hcl
          targets: default 
